### ISSUE TITLE
Can't parse .dot file where a node is in quotation marks

### ISSUE THREAD

**Issue by type-tariq** [sehe/spirit-graphviz#2]
When I feed [polblogs.txt](https://github.com/sehe/spirit-graphviz/files/10951417/polblogs.txt) to the parser, the whole file remains as unparsed input:
https://github.com/sehe/spirit-graphviz/blob/3590f8500dbca93fb307e97dfb433a8514c667f2/spirit-graphviz.cpp#L39
I am guessing it is because the nodes are in quotation marks, but I do not understand how to update the grammar.

**Comment by sehe** [comment]
A small scan of the code (or the readme and Graphviz syntax) will show you that quotes are not the problem.

Why guess if you can try?

![image](https://user-images.githubusercontent.com/324097/224559716-7cb8b0bb-eaca-46b3-af50-cfcb6ee23a56.png)

Oh. Aha! You can see the culprit now? It's *a lack of quoting*, because the source contains a comma, which is obviously interpreted by graphviz.

You can confirm with e.g. `dot`:

```
dot <(echo 'digraph  { "40ozblog.blogspot.com" [source=Blogarama,BlogCatalog, value=0]; }')
Error: /dev/fd/63: syntax error in line 1 near ','
```

Fixing it in all the 508 lines where it is a problem:

```
Parse success
id:"100monkeystyping.com" owner_id:""
id:"12thharmonic.com/wordpress" owner_id:""
id:"40ozblog.blogspot.com" owner_id:""
id:"4lina.tblog.com" owner_id:""
id:"750volts.blogspot.com" owner_id:""
id:"84rules.blog-city.com" owner_id:""
id:"95theses.blogspot.com" owner_id:""
id:"a100wwe.blogspot.com" owner_id:""
id:"abbadabbaduo.blogspot.com" owner_id:""
id:"aboutpolitics.blogspot.com" owner_id:""
...
id:"xtremerightwing.net" owner_id:""
id:"yarsrevenge.blogspot.com" owner_id:""
id:"yglesias.typepad.com/matthew" owner_id:""
id:"yoder.ru" owner_id:""
id:"youngconservative.blogspot.com" owner_id:""
id:"younglibs.com" owner_id:""
id:"zebrax.blogs.com" owner_id:""
id:"zeke01.blogspot.com" owner_id:""
id:"zeke01.typepad.com" owner_id:""
id:"zeph1z.tripod.com/blog" owner_id:""
Remaining unparsed input: '
'
```

That's output assuming with the demo tweaks from your previous question, otherwise expect:

```
Parse success
// generated from c++
digraph {
    "100monkeystyping.com"[source=Blogarama,value=0];
    "12thharmonic.com/wordpress"[source=BlogCatalog,value=0];
    "40ozblog.blogspot.com"[source="Blogarama,BlogCatalog",value=0];
    "4lina.tblog.com"[source=Blogarama,value=0];
    "750volts.blogspot.com"[source=Blogarama,value=0];
    "95theses.blogspot.com"[source=Blogarama,value=0];
    "abbadabbaduo.blogspot.com"[source="Blogarama,LeftyDirectory",value=0];
    "aboutpolitics.blogspot.com"[source="Blogarama,eTalkingHead",value=0];
 ...
    zeke01.typepad.com -> aldaynet.org;
    zeke01.typepad.com -> blogsagainsthillary.com;
    zeke01.typepad.com -> blogsforbush.com;
    zeke01.typepad.com -> drudgereport.com;
    zeke01.typepad.com -> gevkaffeegal.typepad.com/the_alliance;
    zeke01.typepad.com -> gopbloggers.org;
    zeke01.typepad.com -> homespunbloggers.blogspot.com;
    zeke01.typepad.com -> truthlaidbear.com;
    zeph1z.tripod.com/blog -> anncoulter.org;
}
Remaining unparsed input: '
'
```

**Comment by type-tariq** [comment]
Thank you for pointing it out. I have now read [.dot language](https://graphviz.org/doc/info/lang.html) and [attributes](https://graphviz.org/doc/info/attrs.html) pages, but couldn't find anything that explicitly states that "lists" should be in quotation marks. Since your parsers follows their grammar, does this mean that [polblogs.dot](https://github.com/sehe/spirit-graphviz/files/10951417/polblogs.txt) is an incorrect .dot file?

**Comment by sehe** [comment]
polblogs.dot is invalid graphviz indeed.

There is no concept of a list in the graphviz grammar. It's just attribute values, graphviz doesn't care what they mean. The production for attribute list is:

a_list | : | ID '=' ID [ (';' \\| ',') ] [ a_list ]
-- | -- | --

Looking at `ID` you can conclude that it cannot legally contain a space, **unless** quoted:


> An ID is one of the following:
> 
>  - Any string of alphabetic ([a-zA-Z\200-\377]) characters, underscores ('_') or digits([0-9]), not beginning with a digit;
>  - a numeral [-]?(.[0-9]⁺ | [0-9]⁺(.[0-9]*)? );
>  - any double-quoted string ("...") possibly containing escaped quotes (\\")¹;
>  - an HTML string (<...>).
> 
> An ID is just a string; the lack of quote characters in the first two forms is just for simplicity. There is no semantic difference between abc_2 and "abc_2", or between 2.34 and "2.34". Obviously, to use a keyword as an ID, it must be quoted.

That's all directly from the page you linked.
